apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }
    http {
      upstream ollama_servers {
        server localhost:11434;
        server localhost:11435;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://ollama_servers;
        }
      }
    }
