apiVersion: v1
kind: Pod
metadata:
  name: ollama-pod
  labels:
    app: ollama
spec:
  containers:
  - name: ollama
    image: ollama/ollama:latest
    command: ['sh', '-c', 'ollama start & sleep 10; ollama pull llama3 && tail -f /dev/null']
    ports:
    - containerPort: 11434
    env:
    - name: OLLAMA_MODEL_PATH
      value: /models/
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    volumeMounts:
    - mountPath: /models
      name: model-storage
  volumes:
  - name: model-storage
    emptyDir: {}
  restartPolicy: Always
